### ISSUE TITLE
Simple Write-CUClassDiagram doesnt generate file in same directory

### ISSUE THREAD

**Issue by LxLeChat** [Stephanevg/PSClassUtils#10]
A basic Write-CUCLassDiagram does not generate the image file in the same directory
See Screen:

![image](https://user-images.githubusercontent.com/43340127/45620466-53898580-ba7d-11e8-89df-2619cc6ec305.png)

command is run from "c:\temp" where the class.ps1 file is located.
The result image is generated in "c:\users\<username>"

**Comment by Stephanevg** [comment]
fixed in https://github.com/Stephanevg/PSClassUtils/commit/458af9ef6341ab86fcb8e0fd05be865dff7c641e

**Comment by Stephanevg** [comment]
Issue seems to be still present:

![image](https://user-images.githubusercontent.com/6302961/46541868-62fe3080-c8bd-11e8-8a92-662b52ac221d.png)
