### ISSUE TITLE
Add Function to generate basic Pester tests for classes

### ISSUE THREAD

**Issue by bateskevin** [Stephanevg/PSClassUtils#12]
Add a function that utilises the existing classes to generate basic Pester tests for Powershell classes.

I genreated tests to test if the properties have the correct type for example.

**Comment by Stephanevg** [comment]
Hi, I like the idea of this feature. 
I think that it would not be to difficult to implement using the existing set of functions already existing in the module.

Also, I think this issue could be resolved easier,  once the issue https://github.com/Stephanevg/PSClassUtils/issues/13 is resolved.

**Comment by Stephanevg** [comment]
@bateskevin on a more general note, could make an example of how you would see this feature implemented, so we can discuss the design?

An example of a class, with the Resulted pester tests would be great as a starter for the discussion I think.
