### ISSUE TITLE
Add ClassDiagram of PsClassUtils as part of the document

### ISSUE THREAD

**Issue by Stephanevg** [Stephanevg/PSClassUtils#123]
SHAME ON ME!!!

This is a module helping to generate UML diagrams of your classes for documentation purposes, and I realized today, that we don't even have our Class structured document.
Boooooooo!! 👎 

So, running ```write-CUClassDiagram -Path ./PsClassUtils/Code/``` might suffice

**Comment by tomlarse** [comment]
Do you want it just in the Readme under "Live Examples"?

**Comment by tomlarse** [comment]
Something like this?

https://github.com/tomlarse/PSClassUtils/tree/iss123#psclassutils-1

**Comment by Stephanevg** [comment]
Hi, that would be perfect yes @tomlarse
