### ISSUE TITLE
Installing PSClassUtils

### ISSUE THREAD

**Issue by LxLeChat** [Stephanevg/PSClassUtils#22]
In the readme.md maybe you should change the install part from:
`Find-Module PSClassUtils | Install-Module PSClassUtils`

to:
`Find-Module PSClassUtils | Install-Module`

else an error is thrown !

**Comment by Stephanevg** [comment]
Voila, I did the update. thanks for creating the Issue @LxLeChat !!
https://github.com/Stephanevg/PSClassUtils/blob/master/Readme.md
