### ISSUE TITLE
Add a Scope parameter to the Install-CUDiagramPrerequisites function

### ISSUE THREAD

**Issue by LaurentLienhard** [Stephanevg/PSClassUtils#84]
It would be interesting if we could choose on which scope we want to install the prerequisites modules

**Comment by Stephanevg** [comment]
This is handled through the follwing function: https://github.com/Stephanevg/PSClassUtils/blob/master/PSClassUtils/Functions/Public/Install-CUDiagramPrerequisites.ps1 

I think that this could be implemented by adding an extra -Scope parameter to this function, and simply pass it further down the chain to the ```install-Module``` cmdlet.

**Comment by Stephanevg** [comment]
Done and merged
